### ISSUE TITLE
Excel formulas are not auto calculated upon opening the spreadsheet saved by this library

### ISSUE THREAD

**Issue by nawfalhasan** [svrnm/exceldatatables#1]
**Issue:**
Suppose you have some formula in the pivot/chart sheet that references values from 'Data' sheet. In that case if you dump new data to 'Data' sheet and save it and open it, the formulas are not auto  calculated based on new dumped values in 'Data' sheet. Instead it reflects the old values. 

**Solution:**
This can be trivially fixed though, by having the tag `calcPr` with attribute `fullCalcOnLoad` and value `1` in the saved output (xl/workbook.xml file).

**Comment by svrnm** [comment]
Thanks for reporting this enhancement idea and sorry for the delay. I added an option to update the workbook. It seems to work properly, but maybe you can test, if it also works for you.

**Comment by adael** [comment]
Now you can call to ExcelDatatable::refreshTableRange() function and if you've configured the Excel to automatically refresh data, it does update the charts and everything that has the dynamic table as datasource.

Note that you have to specify the name of the data table (not the sheet, but the table data as shown in the image)

[![dynamic2_2_createtable1.png](http://s16.postimg.org/3qycrd18l/dynamic2_2_createtable1.png)](http://postimg.org/image/gv3x41ta9/)

Example:

    $data = array(array(1,2,3),array(1,2,3));
    $excelDataTable = new ExcelDataTable();
    $excelDataTable
        ->addRows($data)
        ->refreshTableRange('table-name')
        ->attachToFile('./example.xlsx');

**Comment by ebspeter** [comment]
This is working fine, thanks!

**Comment by svrnm** [comment]
Fixed.
