### ISSUE TITLE
How to install on laravel 5.3?

### ISSUE THREAD

**Issue by yoseppiedro** [svrnm/exceldatatables#13]
I'm newbie to laravel and i want to use your great package...

how to install it on laravel 5.3? I already follow your instruction to add it on composer.json and on the service provider..
but still i found this error :
Class 'App\Http\Controllers\Svrnm\ExcelDataTables\ExcelDataTable' not found

Thank you..

**Comment by svrnm** [comment]
Can you show me what you have added to your configuration?

Can you try the following instead of the lines mentione in the README.md:

```php
'providers' => array(
    ...
    Svrnm\ExcelDataTables\ExcelDataTablesServiceProvider:class
)
```

**Comment by svrnm** [comment]
@yoseppiedro - did you have any success with the installation, so I can close this issue?
