### ISSUE TITLE
Laravel 5.4 undefined method share()

### ISSUE THREAD

**Issue by c-barre** [svrnm/exceldatatables#15]
Hi,
I installed svrnm/exceldatatables package on Laravel 5.4 project : 

composer.json : `"svrnm/exceldatatables": "dev-master"`
config/app.php : 
`
'providers' => [
 Svrnm\ExcelDataTables\ExcelDataTablesServiceProvider::class
];
`

The result : 
Call to undefined method App\Services\Application::share();
in ExcelDataTablesServiceProvider.php line 21
 
Did I make a mistake ?
I think it's a similar issue but I don't understand the solution : 
https://github.com/willvincent/feeds/issues/24

**Comment by svrnm** [comment]
Thanks, I assume the fix you mentioned should work.

**Comment by svrnm** [comment]
@c-barre - I merged the fix, so can you please verify that it works for you?

**Comment by c-barre** [comment]
It work ! thanks.
