### ISSUE TITLE
Out of Memory error for very large file

### ISSUE THREAD

**Issue by tplassart** [svrnm/exceldatatables#19]
Hello,

Your program is working very well for most of excel files but I have one with a lot of data which lead to a memory error: 

Out of memory (allocated 1876688896) (tried to allocate 24 bytes) in \vendor\exceldatatables\src\Svrnm\ExcelDataTables\ExcelWorksheet.php on line 258

Do you know if there is a way to make it work ?

Thank in advance

**Comment by svrnm** [comment]
You have to increase the memory limits for PHP, e.g. in the php.ini:

```ini
memory_limit = 4G
```
