### ISSUE TITLE
numFmts element doesn't exist

### ISSUE THREAD

**Issue by elilindner** [svrnm/exceldatatables#2]
Hi,

Had an issue where inserting into a newly created sheet, the element 'numFmts' didn't exist causing an issue. Just needed to add

			if ($numFmts == null) {
				$numFmts = $this->getStyles()->createElement('numFmts');
			}

@ line 228 of ExcelWorkbook.php

Other than that, worked brilliantly for updating the source data of a pivot table.

**Comment by svrnm** [comment]
Thanks for reporting this issue and sorry for the delay. I just added a fix for this issue.

**Comment by svrnm** [comment]
Fixed.
